owners.py: Use bytes when calling mktrans for python3
Running the 'generate-rolls' tool from openstack/election repo under
python3 will result in:

(venv) [tony@thor election]$ generate-rolls
<snip>
Traceback (most recent call last):
  File "/home/tony/projects/openstack/openstack/election/.tox/venv/bin/generate-rolls", line 10, in <module>
    sys.exit(main())
  File "/home/tony/projects/openstack/openstack/election/openstack_election/cmds/generate_rolls.py", line 84, in main
    "-o", args.tag, "-r", args.tag] + MINUS_BOT_ACCOUNTS)
  File "/home/tony/projects/openstack/openstack/election/rolls/owners.py", line 622, in main
    normalized_project = normalize_project(project)
  File "/home/tony/projects/openstack/openstack/election/rolls/owners.py", line 127, in normalize_project
    return project.translate(maketrans(' -', '__')).lower()
TypeError: a bytes-like object is required, not 'str'

This change creates a single translation object as appropriate for the
python version running, and then uses it in normalize_project()

Change-Id: I79f643d5747412ce58139cbb2cf31cfe6f88cd09