Add missing zuul-merger dependency: gitpython
Fixes this issue when using the puppet class { '::zuul' to install zuul:

root@test-3rd-party-jenkins-slave:/opt/zuul/zuul/cmd# ./merger.py -d -c /etc/zuul/zuul.conf
Traceback (most recent call last):
  File "./merger.py", line 110, in <module>
    main()
  File "./merger.py", line 102, in main
    server.main()
  File "./merger.py", line 57, in main
    import zuul.merger.server
  File "/usr/local/lib/python2.7/dist-packages/zuul/merger/server.py", line 22, in <module>
    import merger
  File "/usr/local/lib/python2.7/dist-packages/zuul/merger/merger.py", line 16, in <module>
    import git
  File "/usr/local/lib/python2.7/dist-packages/git/__init__.py", line 28, in <module>
    _init_externals()
  File "/usr/local/lib/python2.7/dist-packages/git/__init__.py", line 22, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH

Change-Id: Ied450054c8de0a48fff90a532614221f605c8e1d