Revert "Initial Fedora 21 nodepool disk-image creation"
This reverts commit 7fab4be0db8233e0225a8f026fabbb80cadff760.

Reverting this because this image does not build and is in a tight loop
of failure.

Logs:
2014-11-21 23:53:14,319 WARNING nodepool.NodePool: Missing disk image devstack-fedora21-dib
2014-11-21 23:53:14,320 DEBUG nodepool.NodePool: Queued image building task for devstack-fedora21-dib
2014-11-21 23:53:14,327 INFO nodepool.DiskImageBuilderThread: Creating image: devstack-fedora21-dib with filename /opt/nodepool_dib/devstack-fedora21-dib-1416613994.qcow2
2014-11-21 23:53:14,340 INFO nodepool.DiskImageBuilderThread: Running disk-image-create -x --no-tmpfs  -o /opt/nodepool_dib/devstack-fedora21-dib-1416613994.qcow2 fedora vm puppet nodepool-base node-devstack
2014-11-21 23:53:14,351 ERROR nodepool.DiskImageBuilderThread: Exception in run method:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nodepool/nodepool.py", line 779, in _buildImage
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execve() arg 3 contains a non-string value

Conflicts:
	modules/openstack_project/templates/nodepool/nodepool.yaml.erb

Change-Id: I0d4e8519972d14fc100f46dae1b4549743b438f2